name: vxdetector
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - flake8
  - nose
  - coverage >= 6  # to ensure lcov option is available
  - pandas
  - samtools==1.11
  - bedtools
  - bowtie2
